#!/bin/bash
#PBS -N test
#PBS -q vulcan_debug
#PBS -l nodes=2:ppn=8:vulcan
#PBS -l walltime=00:05:00
#PBS -V

# get user name
user=`whoami`

# make sure we're in the right directory
cd /clusterfs/vulcan/pscratch/$user/taskfarmer/python

# create job list
shuf examples/commands.txt | head -n 200 > jobs.txt

# delete existing log file
if [ -f log ]; then
	rm log
fi

# load python modules
module load python/2.7.3 mpi4py

# launch task farmer
mpirun -np 16 taskfarmer.py -f jobs.txt -v
