# TaskFarmer makefile
#
# Author : Lester. O. Hedges
# Email  : lester.hedges@gmail.com
# Date   : July 11th 2013

# Load the common configuration file
include ../config.mk

all: taskfarmer

taskfarmer:
	$(CC) taskfarmer.c -o taskfarmer

clean:
	rm -f taskfarmer

.PHONY: all
